<ol class="breadcrumb">
    <li><a href="<?= URL ?>GiaoDien/menu">Home /</a></li>
    <li><a href="<?= URL ?>GiaoDien/menu">Danh Sách Điều Hướng /</a></li>
    <li> Thêm </li>
</ol>
<?php

use Model\Common;
use Module\GiaoDien\Model\Menu\FormMenu;
use Module\GiaoDien\Model\Menu\menu;

$menu = new menu();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Điều Hướng</h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <form action="" method="POST">
                <div class="row">
                    <div class="col-md-8">
                        <?php
                        FormMenu::id(Common::uuid())->render();
                        FormMenu::name()->renderHTML();
                        FormMenu::link()->renderHTML();
                        FormMenu::parent_id()->renderHTML();
                        FormMenu::icon()->renderHTML();
                        FormMenu::group_id()->renderHTML();
                        FormMenu::stt()->renderHTML();
                        ?>
                    </div>
                </div>
                <button type="submit" name="Luu" style="float:right" class="btn btn-md btn-primary">Thêm Điều Hướng</button>
            </form>
        </div>
    </div>
    <script>
        // CKEDITOR.editorConfig = function(config) {
        //     config.language = 'es';
        //     config.uiColor = '#F7B42C';
        //     config.height = 300;
        //     config.toolbarCanCollapse = true;
        // };
    </script>
</div>