<ol class="breadcrumb">
    <li><a href="<?= URL ?>GiaoDien/branch">Home /</a></li>
    <li><a href="<?= URL ?>GiaoDien/branch">Danh Sách Branch /</a></li>
    <li> Thêm </li>
</ol>
<?php

use Model\Common;
use Module\GiaoDien\Model\Branch\BranchService;
use Module\GiaoDien\Model\Branch\FormBranch;

$branch = new BranchService();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Cửa Hàng</h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-6">
                        <?php
                        FormBranch::id(Common::uuid())->render();
                        FormBranch::name()->renderHTML();
                        FormBranch::address()->renderHTML();
                        FormBranch::group_id()->renderHTML();
                        ?>
                        <img src="/public/admin/img/no-image.jpg" width="200px" height="200px" id="branchImg" alt="">
                        <input onchange="BrowseServer('branchInput','branchImg')" name="image" id="branchInput" type="file" class="from-control">
                    </div>

                </div>
                <button type="submit" name="Luu" style="float:right" class="btn btn-md btn-primary">Thêm Cửa Hàng</button>
            </form>
        </div>
    </div>
    <script>
        // CKEDITOR.editorConfig = function(config) {
        //     config.language = 'es';
        //     config.uiColor = '#F7B42C';
        //     config.height = 300;
        //     config.toolbarCanCollapse = true;
        // };
    </script>
</div>