<ol class="breadcrumb" >
    <li><a href="<?= URL ?>QuanLyQuyenChiTiet/index" >Home /</a></li>
    <li><a href="<?= URL ?>QuanLyQuyenChiTiet/index" > Danh Sách Quyền Chi Tiết /</a></li>
    <li> Thêm </li>
</ol>
<?php
?>
<div class="container-fluid" >
    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Thêm Quyền Chi Tiết</h3>
            <div class="box-tools" >
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body" >
            <form action="" method="POST">
                <div class="row" >
                    <div class="col-md-6" >
                        <div class="form-group" >
                            <label>Mã</label>
                            <input required="" readonly class="form-control" name="id" value="<?php echo \Model\Common::uuid() ?>" placeholder="Mã" type="Text"  >
                        </div>
                        <div class="form-group" >
                            <label>Tên</label>
                            <select name="user" id="input" class="form-control" required="required">
                                <?php
                                foreach($dataUser as $val){
                                ?>
                                <option value="<?= $val->id?>"><?= $val->username ?></option>
                                <?php 
                                    }
                                ?>
                            </select>
                        </div>
                        <div class="form-group" >
                            <label>Mô Tả</label>
                            <select name="role" id="input" class="form-control" required="required">
                                <?php
                                    foreach($dataRole as $val){
                                ?>
                                <option value="<?= $val->name?>"><?= $val->name ?></option>
                                <?php 
                                    }
                                ?>
                            </select>
                        </div>
                        <div class="form-group" > 
                            <button class="btn btn-default"  type="reset" >Làm Lại</button>
                            <button class="btn btn-success" name="Luu" >Lưu</button>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>


</div>