<!DOCTYPE html>
<html lang="en">
<?php

use Views\theme\backend\block\block;
use Views\theme\molicha\block\block as BlockBlock;

block::head();
block::js();
?>
<body>
    
</body>
</html>
<?php
// var_dump($_SESSION[QuanLy]);
$modelUser = Model\User::CurrentUser();
?>
<?php 
BlockBlock::nav();
?>
<div style="padding-left: 0;" class="container" >
    <ol class="breadcrumb" >
        <li><a href="<?php URL ?>" >Home/</a></li> 
        <li> Tài Khoản </li>
    </ol>
    <div class="row" >
        <div class="col-md-6" >
            <div class="box box-primary" >
                <div class="box-header" >
                    <h3 class="box-title" >Thông Tin Chung</h3>
                    <div class="box-tools" >
                        <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
                    </div>
                </div>
                <div class="box-body" > 
                    <form action="" id="form-profile" method="POST">
                        <?php
                        \Model\Users\FormUser::id($modelUser->id)->render();
                        \Model\Users\FormUser::username($modelUser->username)->renderHTML();
                        \Model\Users\FormUser::fullname($modelUser->fullname)->renderHTML();
                        \Model\Users\FormUser::email($modelUser->email)->renderHTML();
                        ?>  
                        <div class="form-group " >  
                            <button class="btn btn-default" id="resetform"  type="reset" >Làm Lại</button>
                            <!-- reset form  -->
                            <script>
                                $(document).ready(function () {
                                    $('#resetform').click(function(){
                                        $('#form-profile').reset();
                                    })

                                })
                            </script>
                            <button class="btn btn-success" >Lưu</button>
                        </div>
                    </form>

                </div>
            </div>
        </div> 
        <div class="col-md-6" >
            <form method="POST" action="">
                <div class="box box-primary" >
                    <div class="box-header" >
                        <h3 class="box-title" >Bảo Mật</h3> 
                    </div>
                    <div class="box-body" >
                        <div class="form-group" > 
                            <div class="form-group" >
                                <label>Mật Khẩu Cũ</label>
                                <input required="" class="form-control" name="Password" value="" type="password"  >
                            </div>
                            <div class="form-group" >
                                <label>Mật Khẩu Mới</label>
                                <input required="" class="form-control" name="NewPassword" value="" type="password"  >
                            </div>
                            <div class="form-group" >
                                <label>Nhập Lại Mật Khẩu</label>
                                <input required="" class="form-control" name="RePassword" value="" type="password"  >
                            </div>

                        </div> 
                    </div>
                    <div class="box-footer" >
                        <button class="btn btn-success" >Lưu</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>