<ol class="breadcrumb">
    <li><a href="<?= URL ?>SanPham/index">Home /</a></li>
    <li><a href="<?= URL ?>SanPham/index"> Danh Sách Sản Phẩm /</a></li>
    <li> Thêm </li>
</ol>
<?php

use Model\Common;
use Module\SanPham\Model\categoryDetail;
use Module\SanPham\Model\productCategoryDetail;
use Module\SanPham\Model\sanpham;
use Module\SanPham\Model\SanPham\FormSanPham;
use Module\SanPham\Model\Toping;
use Module\SanPham\Model\trangthai;
use Module\SanPham\Model\trangthaichitiet;

$sanpham = new sanpham($dataSanPham);
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Sản Phẩm</h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-5">
                        <?php
                        FormSanPham::id($sanpham->id)->render();
                        FormSanPham::name($sanpham->name)->renderHTML();
                        FormSanPham::code($sanpham->code)->renderHTML();
                        FormSanPham::is_show($sanpham->is_show)->renderHTML();
                        ?>

                        <div class="row">

                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                <?php
                                FormSanPham::price($sanpham->price)->renderHTML();
                                ?>
                            </div>

                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                <?php
                                FormSanPham::sale_off($sanpham->sale_off)->renderHTML();
                                ?>
                            </div>
                        </div>
                        <?php
                        FormSanPham::view($sanpham->view)->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-7">
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="nav-item active">
                                    <a class="nav-link" href="#thumbnail" target="_self" aria-controls="thumbnail" role="tab" data-toggle="tab">Thumbnail</a>
                                </li>
                                <li role="presentation" class="nav-item">
                                    <a class="nav-link" href="#SEO" target="_self" aria-controls="keyword" role="tab" data-toggle="tab">SEO</a>
                                </li>
                                <li role="presentation" class="nav-item">
                                    <a class="nav-link" href="#des" target="_self" aria-controls="des" role="tab" data-toggle="tab">Mô
                                        Tả</a>
                                </li>
                                <li role="presentation" class="nav-item">
                                    <a class="nav-link" href="#category" target="_self" aria-controls="category" role="tab" data-toggle="tab">
                                        Loại Sản Phẩm</a>
                                </li>
                                <li role="presentation" class="nav-item">
                                    <a class="nav-link" href="#trangthai" target="_self" aria-controls="trangthai" role="tab" data-toggle="tab">
                                        Trạng Thái</a>
                                </li>
                                <li role="presentation" class="nav-item">
                                    <a class="nav-link" href="#Toping" target="_self" aria-controls="Toping" role="tab" data-toggle="tab">
                                        Toping</a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel"  class="tab-pane active" id="thumbnail">
                                    <img src="<?= $sanpham->image ?>" width="200px" height="200px" id="thumbnailImg" alt="">
                                    <input onchange="BrowseServer('thumbnailInput','thumbnailImg')" name="image" id="thumbnailInput" type="file" class="from-control">
                                </div>
                                <div role="tabpanel" class="tab-pane" id="SEO">
                                    <?php
                                    FormSanPham::key_word($sanpham->key_word)->renderHTML()
                                    ?>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="category">
                                    <div id="formCategory" style="padding: 0;" class="col-sm-12 d-flex flex-column">
                                        <div class="w-100">
                                            <div style="margin-left: 20px;" data-url="<?php echo URL ?>SanPham/api/CreateLoaiChung" class="form-group float-right btn btn-primary" id="AddLoaiChung">
                                                Thêm Loại Chung
                                            </div>
                                            <div data-url="<?php echo URL ?>SanPham/api/GetDataCreateLoai" class="form-group float-right btn btn-primary" id="categoryAdd">
                                                Thêm Loại Chi Tiết
                                            </div>
                                            <div style="margin-right: 20px;" data-url="<?php echo URL ?>SanPham/api/GetCreateProductChiTiet" data-target="BoxLoaiSPChiTiet" class="form-group float-right btn btn-primary" id="categoryProductAdd">
                                                Thêm Loại Sản Phẩm Chi Tiết
                                            </div>
                                        </div>
                                        <div id="boxAddCategoryChung" class="w-100"></div>
                                        <div id="boxAddCategoryChiTiet" class="w-100"></div>
                                        <div style="font-size: 18px;" class="w-100 text-center">Tên Loại Chi Tiết</div>
                                        <div id="BoxLoaiSPChiTiet"></div>
                                        <div id="boxProductDetailCategory" class="d-flex flex-row">
                                            <div id="cardItemCategory" class="w-100 d-flex flex-wrap row">
                                            <?php

                                            foreach ($dataProductCategoryDetail as $val) {
                                                $productDetailCategory = new productCategoryDetail($val);
                                            ?>
                                                <div data-id="<?php echo $productDetailCategory->id ?>" class="productDetailDelete form-group col-md-6 d-flex align-items-center">
                                                    <div class="w-100">
                                                        <?php
                                                        $categoryDetail = new categoryDetail($productDetailCategory->category_id);
                                                        ?>
                                                        <input type="hidden" style="margin:10px;color:#fff;" value="<?php echo $categoryDetail->id ?>" name="sanpham[productCategoryId][]" class="form-control btn btn-primary" required />
                                                        <input type="text" style="margin:10px;margin-left:5px;color:#fff;" value="<?php echo $categoryDetail->name ?>" class="form-control btn btn-primary" required />
                                                    </div>
                                                    <?php
                                                    $productDetailCategory = new productCategoryDetail($val);
                                                    ?>
                                                    <!-- Xoas loai chi tiet -->
                                                    <button type="button" data-url="<?php echo URL ?>SanPham/api/DeleteLoaiSanPhamChiTiet" data-id="<?php echo $productDetailCategory->id ?>" class="btnProductDetailDelete btn btn-danger ">X</button>
                                                </div>
                                            <?php
                                            }
                                            ?>


                                            </div>

                                        </div>
                                    </div>
                                </div>

                                <div role="tabpanel" class="tab-pane" id="des">
                                    <?php
                                    FormSanPham::des(Common::HTMLdecode($sanpham->des))->renderHTML();
                                    ?>

                                </div>
                                <div id="Toping" role="tabpanel" style="padding: 0;" class="tab-pane"><br>
                                    <div id="formToping" style="padding: 0;" class="col-sm-12 d-flex flex-column">
                                        <div class="w-100">
                                            <div data-url="<?php echo URL ?>SanPham/api/GetDataCreateToping" data-target="cardItemToping" class="form-group float-right btn btn-primary" id="AddToping">
                                                Thêm Toping
                                            </div>
                                        </div>
                                        <div id="cardItemToping" class="w-100">
                                            <div id="boxAddToping" class="w-100 form-group"></div>


                                            <div class="row">
                                                <p style="font-size: 18px;" class="col-md-6 offset-md-3 text-center">Danh Sách Toping</p>
                                            </div>
                                            <?php
                                            foreach ($dataToping as $val) {
                                                $toping = new Toping($val)
                                            ?>
                                                <table data-delete="<?php echo $toping->id ?>" class="table TopingData">
                                                    <tr>
                                                        <td class="border-0">
                                                            <div class="form-group">
                                                                <input class="form-control" name="sanpham[topingName][]" value="<?php echo $toping->name ?>" type="type">
                                                            </div>
                                                        </td>
                                                        <td class="border-0">
                                                            <div class="form-group">
                                                                <button data-url="<?php echo URL ?>SanPham/api/DeleteToping" type="button" data-delete="<?php echo $toping->id ?>" class="btnDeleteToping btn-danger btn">Xoá Toping</button>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>
                                            <?php

                                            }
                                            ?>
                                        </div>
                                    </div>
                                </div>
                                <div id="trangthai" role="tabpanel" style="padding: 0;" class="tab-pane"><br>
                                    <div id="formTrangThai" style="padding: 0;" class="col-sm-12 d-flex flex-column">
                                        <div class="w-100">
                                            <div style="margin-left: 20px;" data-url="<?php echo URL ?>SanPham/api/CreateTrangThaiChung" class="form-group float-right btn btn-primary" id="AddTrangThaiChung">
                                                Thêm Trạng Thái Chung
                                            </div>
                                            <div data-url="<?php echo URL ?>SanPham/api/GetDataCreateTrangThai" data-target="cardItemTrangThai" class="form-group float-right btn btn-primary" id="trangthaiAdd">
                                                Thêm Trạng Thái Chi Tiết
                                            </div>

                                        </div>
                                        <div id="cardItemTrangThai" class="w-100">
                                            <div id="boxAddTrangThaiChung" class="w-100 form-group"></div>
                                            <div class="row">
                                                <div class="col-md-6 text-center">Tên Trạng Thái Chi Tiết</div>
                                                <div class="col-md-6 text-center">Tên Trạng Thái Chung</div>
                                            </div>
                                            <?php
                                            $ttct = new trangthaichitiet();
                                            $datattct = $ttct->GetByProductId($dataSanPham->id);
                                            if (isset($datattct) && !empty($datattct)) {
                                                foreach ($datattct as $ttctItem) {
                                                    $ttct = new trangthaichitiet($ttctItem);
                                            ?>
                                                    <table data-delete="<?php echo $ttct->id ?>" class="table trangThaiData">
                                                        <tr>
                                                            <td class="border-0">

                                                                <input class="form-control" value="<?php echo isset($ttct->name) ? $ttct->name : null ?>" name="sanpham[trangthaichitiet][]" type="hidden">
                                                                <input readonly class="form-control" value="<?php echo isset($ttct->name) ? $ttct->name : null ?>" type="type">
                                        </div>
                                        </td>
                                        <td class="border-0">
                                            <div class="form-group">
                                                <select readonly name="sanpham[trangThaiParentChiTiet][]" class="form-control">
                                                    <?php
                                                    $trangthai = new trangthai($ttct->trang_thai_id);
                                                    ?>
                                                    <option value="<?= $trangthai->id; ?>"><?= $trangthai->name; ?></option>
                                                    <?php
                                                    ?>
                                                </select>
                                            </div>
                                        </td>
                                        <td class="border-0">
                                            <div class="form-group">
                                                <button data-url="<?php echo URL ?>SanPham/api/DeleteTrangThaiChiTiet" data-delete="<?php echo $ttct->id ?>" type="button" class="btnDeleteTrangThai btn-danger btn">Xoá Trạng Thái</button>
                                            </div>
                                        </td>
                                        </tr>
                                        </table>
                                <?php
                                                }
                                            }
                                ?>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        <button type="submit" name="Luu" style="float:right" class="btn btn-md btn-primary">Sửa Sản
            Phẩm</button>
        </form>
    </div>
</div>
<script>
    CKEDITOR.editorConfig = function(config) {
        config.language = 'es';
        config.uiColor = '#F7B42C';
        config.height = 300;
        config.toolbarCanCollapse = true;
    };
</script>
</div>