<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/animate.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/owl.carousel.min.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/owl.theme.default.min.css">

	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/aos.css">

	<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/bootstrap-datepicker.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/jquery.timepicker.css">


	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/flaticon.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/icomoon.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/css/molicha.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/chitietcss/main.css">
	<link rel="stylesheet" href="<?php echo URL; ?>public/molicha/chitietcss/util.css">
	<link rel="icon" type="image/png" href="<?php echo URL ?>public/molicha/images/icons/favicon.png" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/fonts/linearicons-v1.0.0/icon-font.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/slick/slick.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/lightbox2/css/lightbox.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/perfect-scrollbar/perfect-scrollbar.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/noui/nouislider.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="<?php echo URL ?>public/molicha/vendor/slide100/slide100.css">
	<title>Home</title>
</head>
<body class="animsition">
	<!-- content page -->
	<div class="bg0 p-tb-100">
		<div class="container">
			<form>
				<div class="wrap-table-shopping-cart">
					<table class="table-shopping-cart">
						<tr class="table_head bg12">
							<th class="column-1 p-l-30">Product</th>
							<th class="column-2">Price</th>
							<th class="column-3">Quantity</th>
							<th class="column-4">Total</th>
						</tr>

						<tr class="table_row">
							<td class="column-1">
								<div class="flex-w flex-m">
									<div class="wrap-pic-w size-w-50 bo-all-1 bocl12 m-r-30">
										<img src="images/best-sell-01.jpg" alt="IMG">
									</div>

									<span>
										Cheery
									</span>
								</div>
							</td>
							<td class="column-2">
								$ 18.00
							</td>
							<td class="column-3">
								<div class="wrap-num-product flex-w flex-m bg12 p-rl-10">
									<div class="btn-num-product-down flex-c-m fs-29"></div>

									<input class="txt-m-102 cl6 txt-center num-product" type="number" name="num-product1" value="2">

									<div class="btn-num-product-up flex-c-m fs-16"></div>
								</div>
							</td>
							<td class="column-4">
								<div class="flex-w flex-sb-m">
									<span>
										36$
									</span>

									<div class="fs-15 hov-cl10 pointer">
										<span class="lnr lnr-cross"></span>
									</div>
								</div>
							</td>
						</tr>

						<tr class="table_row">
							<td class="column-1">
								<div class="flex-w flex-m">
									<div class="wrap-pic-w size-w-50 bo-all-1 bocl12 m-r-30">
										<img src="images/best-sell-02.jpg" alt="IMG">
									</div>

									<span>
										Asparagus
									</span>
								</div>
							</td>
							<td class="column-2">
								$ 12.00
							</td>
							<td class="column-3">
								<div class="wrap-num-product flex-w flex-m bg12 p-rl-10">
									<div class="btn-num-product-down flex-c-m fs-29"></div>

									<input class="txt-m-102 cl6 txt-center num-product" type="number" name="num-product2" value="1">

									<div class="btn-num-product-up flex-c-m fs-16"></div>
								</div>
							</td>
							<td class="column-4">
								<div class="flex-w flex-sb-m">
									<span>
										12$
									</span>

									<div class="fs-15 hov-cl10 pointer">
										<span class="lnr lnr-cross"></span>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>

				<div class="flex-w flex-sb-m p-t-20">
					<div class="flex-w flex-m m-r-50 m-tb-10">
						<input class="size-a-31 bo-all-1 bocl15 txt-s-123 cl6 plh1 p-rl-20 focus1 m-r-30 m-tb-10" type="text" name="coupon" placeholder="Coupon Code">

						<div class="flex-c-m txt-s-105 cl0 bg10 size-a-32 hov-btn2 trans-04 pointer p-rl-10 m-tb-10">
							apply coupon
						</div>
					</div>

					<div class="flex-c-m txt-s-105 cl0 bg10 size-a-33 hov-btn2 trans-04 pointer p-rl-10 m-tb-10">
						update CART
					</div>
				</div>

				<div class="flex-col-l p-t-68">
					<span class="txt-m-123 cl3 p-b-18">
						CART TOTALS
					</span>
					
					<div class="flex-w flex-m bo-b-1 bocl15 w-full p-tb-18">
						<span class="size-w-58 txt-m-109 cl3">
							Subtotal
						</span>

						<span class="size-w-59 txt-m-104 cl6">
							48$
						</span>
					</div>

					<div class="flex-w flex-m bo-b-1 bocl15 w-full p-tb-18">
						<span class="size-w-58 txt-m-109 cl3">
							Total
						</span>

						<span class="size-w-59 txt-m-104 cl10">
							48$
						</span>
					</div>

					<button class="flex-c-m txt-s-105 cl0 bg10 size-a-34 hov-btn2 trans-04 p-rl-10 m-t-43">
						proceed to checkout
					</button>
				</div>
			</form>
		</div>
	</div>

	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<span class="lnr lnr-chevron-up"></span>
		</span>
	</div>

	

<<script src="<?php echo URL; ?>public/molicha/chitietjs/contact.js"></script>
	<script src="<?php echo URL; ?>public/molicha/chitietjs/main.js"></script>
	<script src="<?php echo URL; ?>public/molicha/chitietjs/map-custom.js"></script>
	<script src="<?php echo URL; ?>public/molicha/chitietjs/revo-custom.js"></script>
	<script src="<?php echo URL; ?>public/molicha/chitietjs/slick-custom.js"></script>
	<script src="<?php echo URL; ?>public/molicha/chitietjs/slide100-custom.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery-migrate-3.0.1.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/bootstrap.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery.waypoints.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery.stellar.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/owl.carousel.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery.magnific-popup.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/aos.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery.animateNumber.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/bootstrap-datepicker.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/jquery.timepicker.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/js/scrollax.min.js"></script>
	<script src="<?php echo URL; ?>public/molicha/mine-config.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/bootstrap/js/popper.js"></script>
	<script src="<?php echo URL ?>public/molicha/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/daterangepicker/moment.min.js"></script>
	<script src="<?php echo URL ?>public/molicha/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/slick/slick.min.js"></script>
	<script src="<?php echo URL ?>public/molicha/js/slick-custom.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/parallax100/parallax100.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/lightbox2/js/lightbox.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/isotope/isotope.pkgd.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/sweetalert/sweetalert.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/noui/nouislider.min.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/vendor/slide100/slide100.js"></script>
	<script src="<?php echo URL ?>public/molicha/chitietjs/slide100-custom.js"></script>
	<!--===============================================================================================-->
	<script src="<?php echo URL ?>public/molicha/chitietjs/main.js"></script>
</body>
</html>