<ol class="breadcrumb">
    <li><a href="<?= URL ?>SanPham/CategoryDetail">Home /</a></li>
    <li><a href="<?= URL ?>SanPham/CategoryDetail">Danh Sách Loại /</a></li>
    <li> Thêm </li>
</ol>
<?php

use Model\Common;
use Module\SanPham\Model\categoryDetail;
use Module\SanPham\Model\CategoryDetail\FormCategoryDetail;

$branch = new categoryDetail();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Loại </h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <form action="" method="POST">
                <div class="row">
                    <div class="col-md-6">
                        <?php
                        FormCategoryDetail::id(Common::uuid())->render();
                        FormCategoryDetail::name($branch->name)->renderHTML();
                        FormCategoryDetail::category_id($branch->category_id)->renderHTML();
                        FormCategoryDetail::des($branch->des)->renderHTML();
                        ?>
                    </div>

                </div>
                <button type="submit" name="Luu" style="float:right" class="btn btn-md btn-primary">Thêm Loại Chi Tiết</button>
            </form>
        </div>
    </div>
    <script>
        // CKEDITOR.editorConfig = function(config) {
        //     config.language = 'es';
        //     config.uiColor = '#F7B42C';
        //     config.height = 300;
        //     config.toolbarCanCollapse = true;
        // };
    </script>
</div>