<?php

use Model\Common;
use Module\Cart\Model\giohang;
use Module\SanPham\Model\sanpham;
use Module\GiaoDien\Model\Menu\menu;
use Module\SanPham\Model\Category;
use Module\SanPham\Model\categoryDetail;
use Views\theme\molicha\block\block1;

?>
<!DOCTYPE html>
<html lang="en">

<?php
block1::head();
?>

<body class="animsition">
	<?php
	block1::header();
	?>
	<!-- Title page -->
	<section class="how-overlay2 bg-img1" style="background-image: url(images/bg-07.jpg);">
		<div class="container">
			<div class="txt-center p-t-160 p-b-165">
				<h2 class="txt-l-101 cl0 txt-center p-b-14 respon1">
					shop
				</h2>

				<span class="txt-m-201 cl0 flex-c-m flex-w">
					<a href="index.html" class="txt-m-201 cl0 hov-cl10 trans-04 m-r-6">
						Home
					</a>

					<span>
						/ Products
					</span>
				</span>
			</div>
		</div>
	</section>

	<!-- Content page -->
	<div class="bg0 p-t-85 p-b-95">
		<div class="container">


			<!-- Shop grid -->
			<div class="shop-grid">
				<div class="row">

					<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
						<div class="list-group">
							<?php
							$categoryDetail = new categoryDetail();
							foreach ($menu as $val) {
								$item = $categoryDetail->GetByCategoryId($val->id);
								if (count($item) > 0) {
							?>
									<a class="btn btn-primary disabled" href="#" role="button"><?= $val->name ?></a>
								<?php

								}
								foreach ($item as $menu) {
								?>
									<a href="<?= $menu->name  ?>.html" class="list-group-item"><?= $menu->name ?></a>
							<?php
								}
							}
							?>
						</div>
					</div>

					<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<div class="flex-w flex-r-m p-b-45 flex-row-rev">
									<div class="flex-w flex-m p-tb-8">


										<div class="flex-w flex-m m-tb-7">
											<button class="dis-block lh-00 pos-relative how-icon1 m-r-15 js-show-list">
												<img class="icon-main trans-04" src="/public/molicha/images/icons/icon-menu-list.png" alt="ICON">
												<img class="ab-t-l icon-hov trans-04" src="/public/molicha/images/icons/icon-menu-list1.png" alt="ICON">
											</button>

											<button class="dis-block lh-00 pos-relative how-icon1 menu-active js-show-grid">
												<img class="icon-main trans-04" src="/public/molicha/images/icons/icon-grid.png" alt="ICON">
												<img class="ab-t-l icon-hov trans-04" src="/public/molicha/images/icons/icon-grid1.png" alt="ICON">
											</button>
										</div>
									</div>

									<span class="txt-s-101 cl9 m-r-30 size-w-53">
										Showing 1–12 of 23 results
									</span>
								</div>
								<div class="row">

									<?php
									foreach ($danhMucChiTietItem as $key => $value) {
										$sp = new sanpham($value->product_id);
									?>

										<!-- - -->
										<div class="col-sm-6 col-md-4 col-lg-3 p-b-30">
											<!-- Block1 -->
											<div class="block1">
												<div class="block1-bg wrap-pic-w bo-all-1 bocl12 hov3 trans-04">
													<img src="<?= $sp->image ?>" alt="IMG">

													<div class="block1-content flex-col-c-m p-b-46">
														<a href="san-pham-chi-tiet/<?= $sp->name ?>.html" class="txt-m-103 cl3 txt-center hov-cl10 trans-04 js-name-b1">
															<?= $sp->name ?>
														</a>

														<span class="block1-content-more txt-m-104 cl9 p-t-21 trans-04">
															<?= Common::PriceToVnd($sp->price) ?>
														</span>

														<div class="block1-wrap-icon flex-c-m flex-w trans-05">
															<a href="san-pham-chi-tiet/<?= $sp->name ?>.html" class="block1-icon flex-c-m wrap-pic-max-w">
																<img src="/public/molicha/images/icons/icon-view.png" alt="ICON">
															</a>
															<!-- <button data-url="/Cart/api/ThemGioHang" value="Add to cart" type="button" id="AddToCart" class="flex-c-m txt-s-103 cl0 bg10 size-a-2 hov-btn2 trans-04 m-b-30">Thêm Vào Giỏ Hàng</button> -->
															<!-- <button data-url="/Cart/api/ThemGioHang" value="Add to cart" type="button" id="AddToCart" class="flex-c-m txt-s-103 cl0 bg10 size-a-2 hov-btn2 trans-04 m-b-30">Thêm Vào Giỏ Hàng</button> -->
															<input type="hidden" id="product_id" data-productid="<?php echo $sp->id ?>">
															<input class="form-control" type="hidden" value="1" id="numberProduct" name="number">


															<button data-url="/Cart/api/ThemGioHang" type="button" id="AddToCart" class="block1-icon flex-c-m wrap-pic-max-w js-addcart-b1">
																<img src="/public/molicha/images/icons/icon-cart.png" alt="ICON">
															</button>
															<!-- <a href="#" class="block1-icon flex-c-m wrap-pic-max-w js-addcart-b1"> -->
															<!-- </a> -->

														</div>
													</div>
												</div>
											</div>
										</div>

									<?php
									}
									?>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Shop list -->
			<div class="shop-list dis-none">
				<?php
				foreach ($danhMucChiTietItem as $key => $value) {
					$sp = new sanpham($value->product_id);
				?>
					<div class="row p-b-30">
						<div class="col-sm-5 col-md-4 col-lg-3">
							<a href="product-single.html" class="wrap-pic-w bo-all-1 bocl12 hov8 trans-04">
								<img src="<?= $sp->image ?>" alt="PRODUCT">
							</a>
						</div>

						<div class="col-sm-7 col-md-8 col-lg-9">
							<div class="p-t-5 p-b-20">
								<div class="flex-w flex-sb-m">
									<a href="product-single.html" class="txt-m-120 cl3 hov-cl10 trans-04 m-r-20 js-name1">
										<?= $sp->name ?>
									</a>

									<a href="wishlist.html" class="lh-00 pos-relative how-icon1 m-tb-15 js-addwish1">
										<img class="icon-main trans-04" src="/public/molicha/images/icons/icon-heart-color.png" alt="ICON">
										<img class="ab-t-l icon-hov trans-04" src="/public/molicha/images/icons/icon-heart-color2.png" alt="ICON">
									</a>
								</div>

								<span class="txt-m-117 cl9">
									<?= Common::PriceToVnd($sp->price) ?>
								</span>

								<p class="txt-s-101 cl6 p-t-18">
									<?= Common::HTMLdecode($sp->des) ?>
								</p>

								<div class="flex-w p-t-29">
									<button class="flex-c-m txt-s-103 cl0 bg10 size-a-2 hov-btn2 trans-04 js-addcart1">
										Add to cart
									</button>
								</div>
							</div>
						</div>
					</div>
				<?php
				}
				?>
			</div>

			<!-- Pagination -->
		</div>
	</div>

	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<span class="lnr lnr-chevron-up"></span>
		</span>
	</div>


	<?php
	block1::js();
	?>
</body>

</html>