<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?= URL ?>public/admin/css/style.css">
	<link rel="stylesheet" href="<?= URL ?>public/admin/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?= URL ?>public/admin/plugins/fontawesome/css/fontawesome.min.css">
	<link rel="stylesheet" href="<?= URL ?>public/admin/plugins/fontawesome/css/all.min.css">
	<link rel="stylesheet" href="<?= URL ?>public/admin/plugins/select2/css/select2.min.css">

	<!-- Datepicker CSS -->
	<link rel="stylesheet" href="<?= URL ?>public/admin/css/bootstrap-datetimepicker.min.css">

	<!-- quill CSS -->
	<link rel="stylesheet" href="<?= URL ?>public/admin/plugins/quill/css/quill.snow.css">

	<!-- Datatables CSS -->
	<link rel="stylesheet" href="<?= URL ?>public/admin/plugins/datatables/datatables.min.css">
	<!-- sweetalert2 CSS -->
	<link rel="stylesheet" href="<?= URL ?>public/admin/plugins/sweetalert2/sweetalert2.min.css">

	<!-- Main CSS -->
	<link rel="stylesheet" href="<?= URL ?>public/admin/css/style.css">

	<title>Đăng Ký</title>
</head>

<body>
	<div class="main-wrapper login-body">
		<div class="login-wrapper">
			<div class="container">
				<?php
				include_once $_Content;
				?>
			</div>
		</div>
	</div>
</body>

</html>