<?php
                $error = \Model\Error::GetError();
                if ($error != null) {
                    ?> 
                    <div class="system-alert alert alert-<?php echo $error["Type"]; ?> alert-dismissible">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <?php echo $error["Content"]; ?>
                    </div>
                    <?php
                }
                ?>
<?php 
    include $_Content
?>