<?php

use Model\Common;
use Controller\CheckLogin;
use Module\Cart\Model\giohang;
use Module\SanPham\Model\sanpham;
use Module\GiaoDien\Model\Menu\menu;
use Module\SanPham\Model\categoryDetail;

new CheckLogin();

?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="/public/molicha/css/bootstrap.min.css">
	<link rel="stylesheet" href="/public/molicha/css/animate.css">
	<link rel="stylesheet" href="/public/molicha/css/owl.carousel.min.css">
	<link rel="stylesheet" href="/public/molicha/css/owl.theme.default.min.css">

	<link rel="stylesheet" href="/public/molicha/css/aos.css">

	<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

	<link rel="stylesheet" href="/public/molicha/css/bootstrap-datepicker.css">
	<link rel="stylesheet" href="/public/molicha/css/jquery.timepicker.css">


	<link rel="stylesheet" href="/public/molicha/css/flaticon.css">
	<link rel="stylesheet" href="/public/molicha/css/icomoon.css">
	<link rel="stylesheet" href="/public/molicha/css/molicha.css">
	<link rel="stylesheet" href="/public/molicha/chitietcss/main.css">
	<link rel="stylesheet" href="/public/molicha/chitietcss/util.css">
	<link rel="icon" type="image/png" href="/public/molicha/images/icons/favicon.png" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<!--===============================================================================================-->
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/slick/slick.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/lightbox2/css/lightbox.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/perfect-scrollbar/perfect-scrollbar.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/noui/nouislider.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/public/molicha/vendor/slide100/slide100.css">

	<title>Home</title>
</head>

<body class="animsition">
	<!-- Header -->
	<header>
		<!-- Header desktop -->
		<div class="container-menu-desktop">
			<div class="wrap-menu-desktop">
				<nav class="limiter-menu-desktop">
					<div class="left-header">
						<!-- Logo desktop -->
						<div class="logo">
							<a href="/"><img src="/public/molicha/images/icons/logo-01.png" alt="IMG-LOGO"></a>
						</div>
					</div>

					<div class="center-header">
						<!-- Menu desktop -->
						<div class="menu-desktop">
							<ul class="main-menu">
								<?php
								$menu = new menu();
								$dataMenu = $menu->GetItemsByGroupsParent('MainMenu', '');
								foreach ($dataMenu as $menuItem) {
								?>
									<li style="color: #000;" class="nav-item <?php echo ($menuItem->stt == 0) ? 'active' : '' ?> nav-link"><a href="<?= URL .  $menuItem->link; ?>" class="nav-link"><?= $menuItem->name; ?></a></li>
								<?php
								}
								?>
							</ul>
						</div>
					</div>

					<div class="right-header">
						<!-- Icon header -->
						<div class="wrap-icon-header flex-w flex-r-m h-full wrap-menu-click p-t-8">
							
							<div class="wrap-cart-header h-full flex-m m-l-10 menu-click">
								<?php 
									$tongcong = 0;
									$giohang = new giohang();
									$dataGioHang = $giohang->GetByUserId($_SESSION[QuanLy]->id);
								?>
								<div class="icon-header-item flex-c-m trans-04">
									<img src="/public/molicha/images/icons/icon-cart-2.png" alt="CART">
								</div>
								<div id="BoxCart" class="cart-header menu-click-child trans-04">
									<?php
									foreach ($dataGioHang as $val) {
										$giohang = new giohang($val);
									?>
										<div data-cartid="<?php echo $giohang->id ?>" class="cartItem bo-b-1 bocl15">
											<div class="size-h-2 js-pscroll m-r--15 p-r-15">
												<!-- cart header item -->
												<div class="flex-w flex-str m-b-25">
													<div class="size-w-15 flex-w flex-t">
														<?php
														$sp = new sanpham($val->product_id);
														$tongcong += $sp->price;
														?>
														<a href="/sanphamchitiet/<?php echo $sp->name ?>.html" class="wrap-pic-w bo-all-1 bocl12 size-w-16 hov3 trans-04 m-r-14">
															<div class="img-responsive">
																<img style="width: 100%;height: 100%;" src="<?php echo $sp->image ?>" alt="<?php echo $sp->name ?>">
															</div>
														</a>

														<div class="size-w-17 flex-col-l">
															<a href="/sanphamchitiet/<?php echo $sp->name ?>.html" class="txt-s-108 cl3 hov-cl10 trans-04">
																<?php echo $sp->name ?>
															</a>

															<span class="txt-s-101 cl9">
																<?php echo Common::PriceToVnd($sp->price) ?>
															</span>

															<span class="txt-s-109 cl12">
																X<?php
																	$giohang = new giohang($val);
																	echo $giohang->number;
																	?>
															</span>
														</div>
													</div>

													<div class="size-w-14 flex-b">
														<button data-cartid="<?php echo $giohang->id ?>" data-deleteurlcart="/Cart/api/XoaSanPham" id="DeleteCart" class="lh-10">
															<img src="/public/molicha/images/icons/icon-close.png" alt="CLOSE">
														</button>
													</div>
												</div>

												<!-- cart header item -->
											</div>
										</div>
									<?php
									}
									?>
									<div class="flex-w flex-sb-m p-b-31">
										<span class="txt-m-103 cl3 p-r-20">
											Tổng Tiền:
										</span>

										<span class="txt-m-111 cl10">
											<?php echo Common::PriceToVnd($tongcong) ?>
										</span>
									</div>
									<a href="/Cart/Cart/post" class="flex-c-m size-a-8 bg10 txt-s-105 cl13 hov-btn2 trans-04">
										Thanh Toán
									</a>
									<a href="/Cart/cart" style="margin-top: 10px;" class="flex-c-m size-a-8 bg10 txt-s-105 cl13 hov-btn2 trans-04">
										Giỏ Hàng
									</a>
								</div>
							</div>
						</div>
					</div>
				</nav>
			</div>
		</div>
	</header>



	<!-- Product detail -->
	<section class="sec-product-detail bg0 p-t-105 p-b-70">
		<div class="container">
			<div class="row">
				<div class="col-md-7 col-lg-6">
					<div class="m-r--30 m-r-0-lg">
						<!-- Slide 100 -->
						<div id="slide100-01">
							<div class="wrap-main-pic-100 bo-all-1 bocl12 pos-relative">
								<div class="main-frame">
									<div class="wrap-main-pic">
										<div class="main-pic">
											<img src="<?php echo $item->image ?>" alt="IMG-SLIDE">
										</div>
									</div>
								</div>
							</div>

							<div class="wrap-thumb-100 flex-w flex-sb p-t-30">
								<div class="thumb-100">
									<div class="sub-frame sub-1">
										<div class="wrap-main-pic">
											<div class="main-pic">
												<img src="<?php echo $item->image ?>" alt="IMG-SLIDE">
											</div>
										</div>

										<div class="btn-sub-frame btn-1 bo-all-1 bocl12 hov8 trans-04"></div>
									</div>
								</div>

								<div class="thumb-100">
									<div class="sub-frame sub-2">
										<div class="wrap-main-pic">
											<div class="main-pic">
												<img src="<?php echo $item->image ?>" alt="IMG-SLIDE">
											</div>
										</div>

										<div class="btn-sub-frame btn-2 bo-all-1 bocl12 hov8 trans-04"></div>
									</div>
								</div>

								<div class="thumb-100">
									<div class="sub-frame sub-3">
										<div class="wrap-main-pic">
											<div class="main-pic">
												<img src="<?php echo $item->image ?>" alt="IMG-SLIDE">
											</div>
										</div>

										<div class="btn-sub-frame btn-3 bo-all-1 bocl12 hov8 trans-04"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-5 col-lg-6">
					<div class="p-l-70 p-t-35 p-l-0-lg">
						<h4 class="js-name1 txt-l-104 cl3 p-b-16">
							<?php echo $item->name ?>
						</h4>

						<span class="txt-m-117 cl9">
							<?php echo Common::PriceToVnd($item->price) ?> VND
						</span>

				

						<p class="txt-s-101 cl6">
							<?php echo Common::HTMLdecode($item->des) ?>
						</p>
						<div class="flex-w flex-m p-t-55 p-b-30">
							<div class="wrap-num-product flex-w flex-m bg12 p-rl-10 m-r-30 m-b-30">
								<input type="hidden" id="product_id" data-productid="<?php echo $item->id ?>">

								<!-- <input class="txt-m-102 cl6 txt-center num-product" type="number" id="numberProduct" name="number" value="1"> -->
								<input class="form-control" type="number" onKeyDown="return false" value="1" max="10" min="1" id="numberProduct" name="number">
							</div>


							<button data-url="/Cart/api/ThemGioHang" value="Add to cart" type="button" id="AddToCart" class="flex-c-m txt-s-103 cl0 bg10 size-a-2 hov-btn2 trans-04 m-b-30">Thêm Vào Giỏ Hàng</button>

						</div>

						<div class="txt-s-107 p-b-6">
							<span class="cl6">
								Category:
							</span>
							<?php
							$categoryDetail = new categoryDetail($productDetailCategory[0]->category_id);
							?>
							<a href="localhost:8080/danhmuc/<?php echo $categoryDetail->name ?>.html" class="cl9">
								Fruit
							</a>
						</div>

						<div class="txt-s-107 p-b-6">
							<span class="cl6">
								Tags: <?php echo Common::HTMLdecode($item->key_word) ?>
							</span>
						</div>
					</div>
				</div>
			</div>

			<!-- Tab01 -->
			<div class="tab02 p-t-80">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" data-toggle="tab" href="#description" role="tab">Description</a>
					</li>

				
				</ul>

				<!-- Tab panes -->
				<div class="tab-content">
					<!-- - -->
					<div class="tab-pane fade show active" id="description" role="tabpanel">
						<div class="p-t-30">
							<p class="txt-s-112 cl9">
								<?php echo Common::HTMLdecode($item->des) ?>
							</p>
						</div>
					</div>

					
				</div>
			</div> -->
		</div>
		</div>
		</div>
	</section>

	<!-- Related product -->
	<!-- Logo -->


	<!-- Subscribe -->

	<!-- Footer -->
	<footer class="bg12">
		<div class="container">
			<div class="wrap-footer flex-w p-t-60 p-b-62">
				<div class="footer-col1">
					<div class="footer-col-title">
						<a href="#">
							<img src="/public/molicha/images/icons/logo-01.png" alt="LOGO">
						</a>
					</div>

					<p class="txt-s-101 cl6 size-w-10 p-b-16">
						There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
					</p>

					<ul>
						<li class="txt-s-101 cl6 flex-t p-b-10">
							<span class="size-w-11">
								<img src="/public/molicha/images/icons/icon-mail.png" alt="ICON-MAIL">
							</span>

							<span class="size-w-12 p-t-1">
								markrussell@example.com
							</span>
						</li>

						<li class="txt-s-101 cl6 flex-t p-b-10">
							<span class="size-w-11">
								<img src="/public/molicha/images/icons/icon-pin.png" alt="ICON-MAIL">
							</span>

							<span class="size-w-12 p-t-1">
								No 40 Baria Sreet 133/2, NewYork
							</span>
						</li>

						<li class="txt-s-101 cl6 flex-t p-b-10">
							<span class="size-w-11">
								<img src="/public/molicha/images/icons/icon-phone.png" alt="ICON-MAIL">
							</span>

							<span class="size-w-12 p-t-1">
								(785) 977 5767
							</span>
						</li>
					</ul>
				</div>

				<div class="footer-col2">
					<div class="footer-col-title flex-m">
						<span class="txt-m-109 cl3">
							Information
						</span>
					</div>

					<ul>
						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								About our shop
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								Top sellers
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								Our blog
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								New products
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								Secure shopping
							</a>
						</li>
					</ul>
				</div>

				<div class="footer-col3">
					<div class="footer-col-title flex-m">
						<span class="txt-m-109 cl3">
							My Account
						</span>
					</div>

					<ul>
						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								My account
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								Discount
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								Personal information
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								My address
							</a>
						</li>

						<li class="p-b-16">
							<a href="#" class="txt-s-101 cl6 hov-cl10 trans-04 p-tb-5">
								Order history
							</a>
						</li>
					</ul>
				</div>

				<div class="footer-col4">
					<div class="footer-col-title flex-m">
						<span class="txt-m-109 cl3">
							Instagram
						</span>
					</div>

					<div class="flex-w flex-sb p-t-6">
						<div class="size-w-13 m-b-10">
							<a href="#" class="dis-block size-a-7 bg-img1 hov4" style="background-image: url('/public/molicha/images/instagram-01.jpg');"></a>
						</div>

						<div class="size-w-13 m-b-10">
							<a href="#" class="dis-block size-a-7 bg-img1 hov4" style="background-image: url('/public/molicha/images/instagram-02.jpg');"></a>
						</div>

						<div class="size-w-13 m-b-10">
							<a href="#" class="dis-block size-a-7 bg-img1 hov4" style="background-image: url('/public/molicha/images/instagram-03.jpg');"></a>
						</div>

						<div class="size-w-13 m-b-10">
							<a href="#" class="dis-block size-a-7 bg-img1 hov4" style="background-image: url('/public/molicha/images/instagram-04.jpg');"></a>
						</div>

						<div class="size-w-13 m-b-10">
							<a href="#" class="dis-block size-a-7 bg-img1 hov4" style="background-image: url('/public/molicha/images/instagram-05.jpg');"></a>
						</div>

						<div class="size-w-13 m-b-10">
							<a href="#" class="dis-block size-a-7 bg-img1 hov4" style="background-image: url('/public/molicha/images/instagram-06.jpg');"></a>
						</div>
					</div>
				</div>
			</div>

			<div class="flex-w flex-sb-m bo-t-1 bocl14 p-tb-14">
				<span class="txt-s-101 cl9 p-tb-10 p-r-29">
					Copyright © 2017 Organive. All rights reserved.
				</span>

				<div class="flex-w flex-m">
					<a href="#" class="m-r-29 m-tb-10">
						<img src="/public/molicha/images/icons/icon-pay-01.png" alt="ICON-PAY">
					</a>

					<a href="#" class="m-r-29 m-tb-10">
						<img src="/public/molicha/images/icons/icon-pay-02.png" alt="ICON-PAY">
					</a>

					<a href="#" class="m-r-29 m-tb-10">
						<img src="/public/molicha/images/icons/icon-pay-03.png" alt="ICON-PAY">
					</a>

					<a href="#" class="m-r-29 m-tb-10">
						<img src="/public/molicha/images/icons/icon-pay-04.png" alt="ICON-PAY">
					</a>

					<a href="#">
						<img src="/public/molicha/images/icons/icon-pay-05.png" alt="ICON-PAY">
					</a>
				</div>
			</div>
		</div>
	</footer>


	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<span class="lnr lnr-chevron-up"></span>
		</span>
	</div>



	<!--===============================================================================================-->
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/jquery/jquery-3.2.1.min.js"></script>
	<script src="/public/molicha/vendor/animsition/js/animsition.min.js"></script>
	<script src="/public/molicha/chitietjs/contact.js"></script>
	<script src="/public/molicha/chitietjs/revo-custom.js"></script>
	<script src="/public/molicha/chitietjs/map-custom.js"></script>
	<script src="/public/molicha/cart.js"></script>
	<!--===============================================================================================-->
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/bootstrap/js/popper.js"></script>
	<script src="/public/molicha/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/daterangepicker/moment.min.js"></script>
	<script src="/public/molicha/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/slick/slick.min.js"></script>
	<script src="/public/molicha/js/slick-custom.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/parallax100/parallax100.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/lightbox2/js/lightbox.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/isotope/isotope.pkgd.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/sweetalert/sweetalert.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/noui/nouislider.min.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/vendor/slide100/slide100.js"></script>
	<script src="/public/molicha/chitietjs/slide100-custom.js"></script>
	<!--===============================================================================================-->
	<script src="/public/molicha/chitietjs/main.js"></script>

</body>

</html>