<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" type="text/css" href="<?php echo URL .'public/scss/css/login.css' ?>">

	<title>Đăng Nhập</title>
</head>
<body>
	<div class="login">
		<div class="container">
			<?php
				include_once $_Content;
			?>
		</div>
	</div>
</body>
</html>