<ol class="breadcrumb">
    <li><a href="<?= URL ?>GiaoDien/slider">Home /</a></li>
    <li><a href="<?= URL ?>GiaoDien/slider">Danh Sách Slider /</a></li>
    <li> Thêm </li>
</ol>
<?php

use Model\Common;
use Module\GiaoDien\Model\Slider\FormSlider;
use Module\GiaoDien\Model\Slider\sliderservice;

$slider = new sliderservice();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Sliderbar</h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-4">
                        <?php
                        FormSlider::id(Common::uuid())->render();
                        FormSlider::name()->renderHTML();
                        FormSlider::group_id()->renderHTML();
                        FormSlider::is_public()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-8">
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#content" target="__self" aria-controls="content" class="nav-link" role="tab" data-toggle="tab">Content</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="#banner" target="__self" aria-controls="banner" class="nav-link" role="tab" data-toggle="tab">Banner</a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="content">
                                    <?php
                                    FormSlider::content()->renderHTML();
                                    ?>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="banner">
                                    <img src="/public/admin/img/no-image.jpg" width="200px" height="200px" id="bannerImg" alt="">
                                    <input onchange="BrowseServer('bannerInput','bannerImg')" name="image" id="bannerInput" type="file" class="from-control">
                                </div>
                            </div>
                        </div>
                        <button type="submit" name="Luu" style="float:right" class="btn btn-md btn-primary">Thêm Sản
                            Phẩm</button>
                    </div>
            </form>
        </div>
    </div>
    <script>
        // CKEDITOR.editorConfig = function(config) {
        //     config.language = 'es';
        //     config.uiColor = '#F7B42C';
        //     config.height = 300;
        //     config.toolbarCanCollapse = true;
        // };
    </script>
</div>